version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - "@navikt/overhead"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - "@navikt/overhead"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "weekly"

