apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: overhead
  namespace: overhead
  labels:
    team: overhead
spec:
  image: {{ image }}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  ingresses:
    - https://overhead.dev.intern.nav.no
