apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: overhead
  namespace: overhead
  labels:
    team: overhead
spec:
  image: ghcr.io/navikt/{{ image }}
  liveness:
    path: /isalive
  readiness:
    path: /isready
